# Generated by Django 4.1.7 on 2023-04-03 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='issue_type_rel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.issuetype'),
            preserve_default=False,
        ),
    ]
