# Generated by Django 4.2 on 2023-04-06 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_issue_type_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='issue_type_rel',
        ),
        migrations.AlterField(
            model_name='task',
            name='issue_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.issuetype'),
            preserve_default=False,
        ),
    ]
